"""
01_train_rl_agent.py

Train Q-learning agent to control Kuramoto synchronization.
Runs locally, deploys to cluster, submits SLURM job.

Usage:
    python deploy_scripts/01_train_rl_agent.py --condition feedback
    python deploy_scripts/01_train_rl_agent.py --condition shortrest
    python deploy_scripts/01_train_rl_agent.py --condition rest

Author: Clemens Bauer
Date: April 2026
"""

import sys
from pathlib import Path
import subprocess
import py_compile
import argparse

# Add parent to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))
import config

# Parse arguments
parser = argparse.ArgumentParser(description="Train RL agent for specific condition")
parser.add_argument(
    "--condition",
    type=str,
    default="feedback",
    choices=["feedback", "shortrest", "rest"],
    help="Cognitive state: feedback (K=10, R=0.8) | shortrest (K=5, R=0.5) | rest (K=1, R=0.3)"
)
args = parser.parse_args()
CONDITION = args.condition

# Get condition parameters
cond_params = config.get_condition_params(CONDITION)

print(f"\nCondition: {CONDITION.upper()}")
print(f"  Coupling K = {cond_params['kuramoto']['coupling_strength']}")
print(f"  Target R = {cond_params['agent']['r_target']}")
print(f"  Input type = {cond_params['input_type']}")

# ============================================================================
# CLUSTER SCRIPT CONTENT
# ============================================================================

# Build parameter strings
k_coupling = str(cond_params['kuramoto']['coupling_strength'])
k_n_osc = str(cond_params['kuramoto']['n_oscillators'])
k_freq_mean = str(cond_params['kuramoto']['freq_mean'])
k_freq_std = str(cond_params['kuramoto']['freq_std'])
k_dt = str(cond_params['kuramoto']['dt'])

e_alpha = str(cond_params['energy']['alpha'])
e_beta = str(cond_params['energy']['beta'])
e_gamma = str(cond_params['energy']['gamma'])
e_delta = str(cond_params['energy']['delta'])

a_lr = str(cond_params['agent']['learning_rate'])
a_gamma = str(cond_params['agent']['discount_factor'])
a_eps = str(cond_params['agent']['epsilon'])
a_eps_decay = str(cond_params['agent']['epsilon_decay'])
a_r_target = str(cond_params['agent']['r_target'])
a_sync_weight = str(cond_params['agent']['sync_weight'])
a_energy_weight = str(cond_params['agent']['energy_weight'])
a_n_episodes = str(cond_params['agent']['n_episodes'])
a_episode_dur = str(cond_params['agent']['episode_duration'])

input_type = cond_params['input_type']
input_mag = str(cond_params['input_magnitude'])

CLUSTER_SCRIPT = [
    '#!/usr/bin/env python',
    '"""',
    'Train RL agent on cluster - ' + CONDITION + ' condition',
    'Generated by 01_train_rl_agent.py',
    '"""',
    '',
    'import sys',
    'from pathlib import Path',
    'import numpy as np',
    'import pickle',
    '',
    '# Add src to path',
    'SCRIPT_DIR = Path(__file__).parent',
    'SRC_DIR = SCRIPT_DIR.parent / "src"',
    'sys.path.insert(0, str(SRC_DIR))',
    '',
    'from models.kuramoto import KuramotoModel, KuramotoParams',
    'from models.energy import EnergyFunction, EnergyParams',
    'from models.agents import QLearningAgent, AgentParams',
    '',
    'CONDITION = "' + CONDITION + '"',
    '',
    '# ============================================================================',
    '# ENVIRONMENT CLASS',
    '# ============================================================================',
    '',
    'class SynchronizationEnvironment:',
    '    def __init__(self, kuramoto_params, energy_params, episode_duration, target_sync, input_type, input_mag):',
    '        self.kuramoto = KuramotoModel(kuramoto_params)',
    '        self.energy_fn = EnergyFunction(energy_params)',
    '        self.episode_duration = episode_duration',
    '        self.target_sync = target_sync',
    '        self.input_type = input_type',
    '        self.input_mag = input_mag',
    '        self.dt = kuramoto_params.dt',
    '        self.n_steps = int(episode_duration / self.dt)',
    '        self.current_step = 0',
    '        self.sync_history = []',
    '        self.energy_history = []',
    '    ',
    '    def reset(self):',
    '        self.kuramoto.reset(random_phases=True)',
    '        self.current_step = 0',
    '        R = self.kuramoto.step()',
    '        self.sync_history = [R]',
    '        E = self.energy_fn.compute_energy(np.array([R]), dt=self.dt)[0]',
    '        self.energy_history = [E]',
    '        return R, E',
    '    ',
    '    def step(self, action):',
    '        # Apply action based on input type',
    '        if self.input_type == "uniform":',
    '            external_input = np.ones(self.kuramoto.params.n_oscillators) * action',
    '        elif self.input_type == "split":',
    '            external_input = np.zeros(self.kuramoto.params.n_oscillators)',
    '            external_input[:15] = action',
    '            external_input[15:] = -action',
    '        else:  # none',
    '            external_input = np.zeros(self.kuramoto.params.n_oscillators)',
    '        ',
    '        R_next = self.kuramoto.step(external_input)',
    '        self.sync_history.append(R_next)',
    '        sync_array = np.array(self.sync_history)',
    '        E_array = self.energy_fn.compute_energy(sync_array, dt=self.dt)',
    '        E_next = E_array[-1]',
    '        self.energy_history.append(E_next)',
    '        reward = -abs(self.target_sync - R_next) * 100.0 - E_next',
    '        self.current_step += 1',
    '        done = self.current_step >= self.n_steps',
    '        return R_next, E_next, reward, done',
    '',
    '# ============================================================================',
    '# TRAINING',
    '# ============================================================================',
    '',
    'def train_agent(agent, env, n_episodes):',
    '    episode_rewards = []',
    '    episode_sync_means = []',
    '    episode_energy_means = []',
    '    ',
    '    for episode in range(n_episodes):',
    '        R, E = env.reset()',
    '        episode_reward = 0.0',
    '        ',
    '        while True:',
    '            action_idx, action_value = agent.select_action(R, E)',
    '            R_next, E_next, reward, done = env.step(action_value)',
    '            agent.update(R, E, action_idx, R_next, E_next, reward)',
    '            episode_reward += reward',
    '            R, E = R_next, E_next',
    '            if done:',
    '                break',
    '        ',
    '        agent.decay_epsilon()',
    '        episode_rewards.append(episode_reward)',
    '        episode_sync_means.append(np.mean(env.sync_history))',
    '        episode_energy_means.append(np.mean(env.energy_history))',
    '        ',
    '        if (episode + 1) % 10 == 0:',
    '            print("Episode " + str(episode+1) + ": " +',
    '                  "Reward=" + str(round(episode_reward, 2)) + ", " +',
    '                  "R=" + str(round(episode_sync_means[-1], 3)) + ", " +',
    '                  "E=" + str(round(episode_energy_means[-1], 2)))',
    '    ',
    '    return {',
    '        "episode_rewards": episode_rewards,',
    '        "episode_sync_means": episode_sync_means,',
    '        "episode_energy_means": episode_energy_means,',
    '        "epsilon_history": agent.epsilon_history',
    '    }',
    '',
    '# ============================================================================',
    '# MAIN',
    '# ============================================================================',
    '',
    'if __name__ == "__main__":',
    '    print("=" * 70)',
    '    print("Training RL Agent: " + CONDITION)',
    '    print("=" * 70)',
    '    ',
    '    # Initialize from config',
    '    kuramoto_params = KuramotoParams(',
    '        n_oscillators=' + k_n_osc + ',',
    '        coupling_strength=' + k_coupling + ',',
    '        freq_mean=' + k_freq_mean + ',',
    '        freq_std=' + k_freq_std + ',',
    '        dt=' + k_dt,
    '    )',
    '    ',
    '    energy_params = EnergyParams(',
    '        alpha=' + e_alpha + ',',
    '        beta=' + e_beta + ',',
    '        gamma=' + e_gamma + ',',
    '        delta=' + e_delta,
    '    )',
    '    ',
    '    agent_params = AgentParams(',
    '        learning_rate=' + a_lr + ',',
    '        discount_factor=' + a_gamma + ',',
    '        epsilon=' + a_eps + ',',
    '        epsilon_decay=' + a_eps_decay + ',',
    '        r_target=' + a_r_target,
    '    )',
    '    ',
    '    # Create environment',
    '    env = SynchronizationEnvironment(',
    '        kuramoto_params,',
    '        energy_params,',
    '        episode_duration=' + a_episode_dur + ',',
    '        target_sync=' + a_r_target + ',',
    '        input_type="' + input_type + '",',
    '        input_mag=' + input_mag,
    '    )',
    '    ',
    '    agent = QLearningAgent(agent_params)',
    '    ',
    '    # Train',
    '    print("Training...")',
    '    results = train_agent(agent, env, n_episodes=' + a_n_episodes + ')',
    '    ',
    '    # Save',
    '    output_dir = Path("/projects/swglab/data/DMNELF/analysis/MNE/jupyter/adaptive_sync_dmnelf/models")',
    '    output_dir.mkdir(exist_ok=True, parents=True)',
    '    ',
    '    agent_path = output_dir / ("qlearning_" + CONDITION + ".pkl")',
    '    agent.save(str(agent_path))',
    '    print("Saved agent: " + str(agent_path))',
    '    ',
    '    results_path = output_dir / ("results_" + CONDITION + ".pkl")',
    '    with open(results_path, "wb") as f:',
    '        pickle.dump(results, f)',
    '    print("Saved results: " + str(results_path))',
    '    ',
    '    print("\\nFinal: Reward=" + str(round(results["episode_rewards"][-1], 2)) +',
    '          " R=" + str(round(results["episode_sync_means"][-1], 3)) +',
    '          " E=" + str(round(results["episode_energy_means"][-1], 2)))',
]

# ============================================================================
# SLURM SUBMISSION SCRIPT
# ============================================================================

SLURM_SCRIPT = [
    '#!/bin/bash',
    '#SBATCH --job-name=rl_' + CONDITION,
    '#SBATCH --partition=' + config.SLURM_PARTITION,
    '#SBATCH --time=' + config.SLURM_TIME,
    '#SBATCH --cpus-per-task=' + str(config.SLURM_CPUS),
    '#SBATCH --mem=' + config.SLURM_MEM,
    '#SBATCH --output=' + str(config.CLUSTER_LOGS / ('rl_' + CONDITION + '_%j.out')),
    '#SBATCH --error=' + str(config.CLUSTER_LOGS / ('rl_' + CONDITION + '_%j.err')),
    '',
    'echo "======================================================="',
    'echo "Training RL Agent: ' + CONDITION + '"',
    'echo "Job ID: $SLURM_JOB_ID"',
    'echo "======================================================="',
    '',
    '# Use base conda environment',
    'source /shared/EL9/explorer/anaconda3/2024.06/etc/profile.d/conda.sh',
    '',
    '# Run training script',
    'python ' + str(config.CLUSTER_SCRIPTS / '01_train_rl_agent_cluster.py'),
    '',
    'echo "======================================================="',
    'echo "Complete: ' + CONDITION + '"',
    'echo "======================================================="',
]

# ============================================================================
# DEPLOYMENT
# ============================================================================

def compile_check():
    """Verify script compiles"""
    temp_file = Path("/tmp/01_train_rl_agent_cluster.py")
    with open(temp_file, 'w') as f:
        f.write('\n'.join(CLUSTER_SCRIPT))
    
    try:
        py_compile.compile(str(temp_file), doraise=True)
        print("✓ Cluster script compiles")
        temp_file.unlink()
        return True
    except py_compile.PyCompileError as e:
        print(f"✗ Compilation error: {e}")
        return False

def deploy_to_cluster():
    """Deploy scripts to cluster"""
    print("\n1. Creating cluster directories...")
    
    dirs = [
        config.CLUSTER_BASE,
        config.CLUSTER_SCRIPTS,
        config.CLUSTER_LOGS,
        config.CLUSTER_MODELS,
        config.CLUSTER_RESULTS
    ]
    
    for d in dirs:
        cmd = "mkdir -p " + str(d)
        subprocess.run(config.ssh_command(cmd), shell=True, check=True)
    
    print("   ✓ Directories created")
    
    # Copy cluster Python script
    print("\n2. Copying cluster script...")
    local_cluster_script = config.LOCAL_SCRIPTS / "01_train_rl_agent_cluster.py"
    with open(local_cluster_script, 'w') as f:
        f.write('\n'.join(CLUSTER_SCRIPT))
    
    cmd = config.scp_to_cluster(
        local_cluster_script,
        config.CLUSTER_SCRIPTS / "01_train_rl_agent_cluster.py"
    )
    subprocess.run(cmd, shell=True, check=True)
    print("   ✓ Python script copied")
    
    # Copy SLURM script
    print("\n3. Copying SLURM script...")
    local_slurm_script = config.LOCAL_SCRIPTS / "01_train_rl_agent.sh"
    with open(local_slurm_script, 'w') as f:
        f.write('\n'.join(SLURM_SCRIPT))
    
    cmd = config.scp_to_cluster(
        local_slurm_script,
        config.CLUSTER_SCRIPTS / "01_train_rl_agent.sh"
    )
    subprocess.run(cmd, shell=True, check=True)
    print("   ✓ SLURM script copied")
    
    # Copy source modules
    print("\n4. Copying source modules...")
    
    # Create src/models directory
    cmd = "mkdir -p " + str(config.CLUSTER_BASE / 'src' / 'models')
    subprocess.run(config.ssh_command(cmd), shell=True, check=True)
    
    src_modules = ['kuramoto.py', 'energy.py', 'agents.py']
    for module in src_modules:
        local_file = config.LOCAL_BASE / 'src' / 'models' / module
        cluster_file = config.CLUSTER_BASE / 'src' / 'models' / module
        
        cmd = config.scp_to_cluster(local_file, cluster_file)
        subprocess.run(cmd, shell=True, check=True)
    
    print("   ✓ Source modules copied")

def submit_job():
    """Submit SLURM job"""
    print("\n5. Submitting SLURM job...")
    
    cmd = "sbatch " + str(config.CLUSTER_SCRIPTS / '01_train_rl_agent.sh')
    result = subprocess.run(
        config.ssh_command(cmd),
        shell=True,
        capture_output=True,
        text=True
    )
    
    if result.returncode == 0:
        job_id = result.stdout.strip().split()[-1]
        print(f"   ✓ Job submitted: {job_id}")
        return job_id
    else:
        print(f"   ✗ Submission failed: {result.stderr}")
        return None

# ============================================================================
# MAIN
# ============================================================================

if __name__ == "__main__":
    print("=" * 70)
    print("Deploy: Train RL Agent - " + CONDITION.upper())
    print("=" * 70)
    
    # Compile check
    if not compile_check():
        sys.exit(1)
    
    # Deploy
    try:
        deploy_to_cluster()
        job_id = submit_job()
        
        if job_id:
            print("\n" + "=" * 70)
            print("Deployment successful!")
            print("=" * 70)
            print(f"\nCondition: {CONDITION}")
            print(f"Job ID: {job_id}")
            print(f"\nExpected result: R ≈ {cond_params['agent']['r_target']}")
            print("\nMonitor:")
            print(f"  ssh {config.CLUSTER_USER}@{config.CLUSTER_HOST} 'tail -f {config.CLUSTER_LOGS}/rl_{CONDITION}_{job_id}.out'")
    
    except Exception as e:
        print(f"\n✗ Deployment failed: {e}")
        sys.exit(1)