"""
01_train_rl_agent.py

Train Q-learning agent to control Kuramoto synchronization.
Runs locally, deploys to cluster, submits SLURM job.

Usage:
    python deploy_scripts/01_train_rl_agent.py

Author: Clemens Bauer
Date: April 2026
"""

import sys
from pathlib import Path
import subprocess
import py_compile

# Add parent to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))
import config

# ============================================================================
# CLUSTER SCRIPT CONTENT
# ============================================================================

CLUSTER_SCRIPT = [
    '#!/usr/bin/env python',
    '"""',
    'Train RL agent on cluster',
    'Generated by 01_train_rl_agent.py',
    '"""',
    '',
    'import sys',
    'from pathlib import Path',
    'import numpy as np',
    'import pickle',
    '',
    '# Add src to path',
    'SCRIPT_DIR = Path(__file__).parent',
    'SRC_DIR = SCRIPT_DIR.parent / "src"',
    'sys.path.insert(0, str(SRC_DIR))',
    '',
    'from models.kuramoto import KuramotoModel, KuramotoParams',
    'from models.energy import EnergyFunction, EnergyParams',
    'from models.agents import QLearningAgent, AgentParams',
    '',
    '# ============================================================================',
    '# ENVIRONMENT CLASS',
    '# ============================================================================',
    '',
    'class SynchronizationEnvironment:',
    '    """Environment for RL agent to control neural synchronization."""',
    '    ',
    '    def __init__(self, kuramoto_params, energy_params, episode_duration=10.0, target_sync=0.9):',
    '        self.kuramoto = KuramotoModel(kuramoto_params)',
    '        self.energy_fn = EnergyFunction(energy_params)',
    '        self.episode_duration = episode_duration',
    '        self.target_sync = target_sync',
    '        self.dt = kuramoto_params.dt',
    '        self.n_steps = int(episode_duration / self.dt)',
    '        self.current_step = 0',
    '        self.sync_history = []',
    '        self.energy_history = []',
    '        self.action_history = []',
    '    ',
    '    def reset(self):',
    '        self.kuramoto.reset(random_phases=True)',
    '        self.current_step = 0',
    '        R = self.kuramoto.step()',
    '        self.sync_history = [R]',
    '        E = self.energy_fn.compute_energy(np.array([R]), dt=self.dt)[0]',
    '        self.energy_history = [E]',
    '        self.action_history = []',
    '        return R, E',
    '    ',
    '    def step(self, action):',
    '        external_input = np.ones(self.kuramoto.params.n_oscillators) * action',
    '        R_next = self.kuramoto.step(external_input)',
    '        self.sync_history.append(R_next)',
    '        sync_array = np.array(self.sync_history)',
    '        E_array = self.energy_fn.compute_energy(sync_array, dt=self.dt)',
    '        E_next = E_array[-1]',
    '        self.energy_history.append(E_next)',
    '        self.action_history.append(action)',
    '        reward = -abs(self.target_sync - R_next) - E_next',
    '        self.current_step += 1',
    '        done = self.current_step >= self.n_steps',
    '        return R_next, E_next, reward, done',
    '',
    '# ============================================================================',
    '# TRAINING FUNCTION',
    '# ============================================================================',
    '',
    'def train_agent(agent, env, n_episodes=100):',
    '    """Train RL agent."""',
    '    episode_rewards = []',
    '    episode_sync_means = []',
    '    episode_energy_means = []',
    '    ',
    '    for episode in range(n_episodes):',
    '        R, E = env.reset()',
    '        episode_reward = 0.0',
    '        ',
    '        while True:',
    '            action_idx, action_value = agent.select_action(R, E)',
    '            R_next, E_next, reward, done = env.step(action_value)',
    '            agent.update(R, E, action_idx, R_next, E_next, reward)',
    '            episode_reward += reward',
    '            R, E = R_next, E_next',
    '            if done:',
    '                break',
    '        ',
    '        agent.decay_epsilon()',
    '        episode_rewards.append(episode_reward)',
    '        episode_sync_means.append(np.mean(env.sync_history))',
    '        episode_energy_means.append(np.mean(env.energy_history))',
    '        ',
    '        if (episode + 1) % 10 == 0:',
    '            print("Episode " + str(episode+1) + ": " +',
    '                  "Reward=" + str(round(episode_reward, 2)) + ", " +',
    '                  "R=" + str(round(episode_sync_means[-1], 3)) + ", " +',
    '                  "E=" + str(round(episode_energy_means[-1], 2)))',
    '    ',
    '    return {',
    '        "episode_rewards": episode_rewards,',
    '        "episode_sync_means": episode_sync_means,',
    '        "episode_energy_means": episode_energy_means,',
    '        "epsilon_history": agent.epsilon_history',
    '    }',
    '',
    '# ============================================================================',
    '# MAIN',
    '# ============================================================================',
    '',
    'if __name__ == "__main__":',
    '    print("=" * 70)',
    '    print("Training RL Agent on Cluster")',
    '    print("=" * 70)',
    '    ',
    '    # Initialize parameters',
    '    kuramoto_params = KuramotoParams(',
    '        n_oscillators=31,',
    '        coupling_strength=5.0,',
    '        freq_mean=10.0,',
    '        freq_std=2.0,',
    '        dt=0.01',
    '    )',
    '    ',
    '    energy_params = EnergyParams(',
    '        alpha=10.01,',
    '        beta=5.00,',
    '        gamma=3.00,',
    '        delta=2.00',
    '    )',
    '    ',
    '    agent_params = AgentParams(',
    '        learning_rate=0.1,',
    '        discount_factor=0.95,',
    '        epsilon=0.3,',
    '        epsilon_decay=0.995,',
    '        r_target=0.9',
    '    )',
    '    ',
    '    # Create environment and agent',
    '    env = SynchronizationEnvironment(',
    '        kuramoto_params,',
    '        energy_params,',
    '        episode_duration=10.0,',
    '        target_sync=0.9',
    '    )',
    '    ',
    '    agent = QLearningAgent(agent_params)',
    '    ',
    '    # Train',
    '    print("Training for 100 episodes...")',
    '    results = train_agent(agent, env, n_episodes=100)',
    '    ',
    '    # Save',
    '    output_dir = Path("/projects/swglab/data/DMNELF/analysis/MNE/jupyter/adaptive_sync_dmnelf/models")',
    '    output_dir.mkdir(exist_ok=True, parents=True)',
    '    ',
    '    agent_path = output_dir / "qlearning_agent.pkl"',
    '    agent.save(str(agent_path))',
    '    print("Saved agent to: " + str(agent_path))',
    '    ',
    '    results_path = output_dir / "training_results.pkl"',
    '    with open(results_path, "wb") as f:',
    '        pickle.dump(results, f)',
    '    print("Saved results to: " + str(results_path))',
    '    ',
    '    # Final stats',
    '    print("\\n" + "=" * 70)',
    '    print("Training Complete!")',
    '    print("=" * 70)',
    '    print("Final episode reward: " + str(round(results["episode_rewards"][-1], 2)))',
    '    print("Final mean R(t): " + str(round(results["episode_sync_means"][-1], 3)))',
    '    print("Final mean E(t): " + str(round(results["episode_energy_means"][-1], 2)))',
]

# ============================================================================
# SLURM SUBMISSION SCRIPT
# ============================================================================

SLURM_SCRIPT = [
    '#!/bin/bash',
    '#SBATCH --job-name=rl_train',
    '#SBATCH --partition=' + config.SLURM_PARTITION,
    '#SBATCH --time=' + config.SLURM_TIME,
    '#SBATCH --cpus-per-task=' + str(config.SLURM_CPUS),
    '#SBATCH --mem=' + config.SLURM_MEM,
    '#SBATCH --output=' + str(config.CLUSTER_LOGS / 'rl_train_%j.out'),
    '#SBATCH --error=' + str(config.CLUSTER_LOGS / 'rl_train_%j.err'),
    '',
    'echo "======================================================="',
    'echo "Training RL Agent"',
    'echo "Job ID: $SLURM_JOB_ID"',
    'echo "======================================================="',
    '',
    '# Load conda',
    'source /shared/EL9/explorer/anaconda3/2024.06/etc/profile.d/conda.sh',
    'conda activate adaptive_sync',
    '',
    '# Run training script',
    'python ' + str(config.CLUSTER_SCRIPTS / '01_train_rl_agent_cluster.py'),
    '',
    'echo "======================================================="',
    'echo "Training complete"',
    'echo "======================================================="',
]

# ============================================================================
# DEPLOYMENT FUNCTIONS
# ============================================================================

def compile_check():
    """Verify script compiles"""
    temp_file = Path("/tmp/01_train_rl_agent_cluster.py")
    with open(temp_file, 'w') as f:
        f.write('\n'.join(CLUSTER_SCRIPT))
    
    try:
        py_compile.compile(str(temp_file), doraise=True)
        print("✓ Cluster script compiles")
        temp_file.unlink()
        return True
    except py_compile.PyCompileError as e:
        print(f"✗ Compilation error: {e}")
        return False

def deploy_to_cluster():
    """Deploy scripts to cluster"""
    print("\n1. Creating cluster directories...")
    
    # Create directories
    dirs = [
        config.CLUSTER_BASE,
        config.CLUSTER_SCRIPTS,
        config.CLUSTER_LOGS,
        config.CLUSTER_MODELS,
        config.CLUSTER_RESULTS
    ]
    
    for d in dirs:
        cmd = f"mkdir -p {d}"
        subprocess.run(config.ssh_command(cmd), shell=True, check=True)
    
    print("   ✓ Directories created")
    
    # Copy Python script
    print("\n2. Copying cluster script...")
    local_cluster_script = config.LOCAL_SCRIPTS / "01_train_rl_agent_cluster.py"
    with open(local_cluster_script, 'w') as f:
        f.write('\n'.join(CLUSTER_SCRIPT))
    
    cmd = config.scp_to_cluster(
        local_cluster_script,
        config.CLUSTER_SCRIPTS / "01_train_rl_agent_cluster.py"
    )
    subprocess.run(cmd, shell=True, check=True)
    print("   ✓ Python script copied")
    
    # Copy SLURM script
    print("\n3. Copying SLURM script...")
    local_slurm_script = config.LOCAL_SCRIPTS / "01_train_rl_agent.sh"
    with open(local_slurm_script, 'w') as f:
        f.write('\n'.join(SLURM_SCRIPT))
    
    cmd = config.scp_to_cluster(
        local_slurm_script,
        config.CLUSTER_SCRIPTS / "01_train_rl_agent.sh"
    )
    subprocess.run(cmd, shell=True, check=True)
    print("   ✓ SLURM script copied")
    
    # Copy src modules
    print("\n4. Copying source modules...")
    src_modules = ['kuramoto.py', 'energy.py', 'agents.py']
    for module in src_modules:
        local_file = config.LOCAL_BASE / 'src' / 'models' / module
        cluster_file = config.CLUSTER_BASE / 'src' / 'models' / module
        
        # Create src/models on cluster
        cmd = f"mkdir -p {config.CLUSTER_BASE / 'src' / 'models'}"
        subprocess.run(config.ssh_command(cmd), shell=True, check=True)
        
        cmd = config.scp_to_cluster(local_file, cluster_file)
        subprocess.run(cmd, shell=True, check=True)
    
    print("   ✓ Source modules copied")

def submit_job():
    """Submit SLURM job"""
    print("\n5. Submitting SLURM job...")
    
    cmd = f"sbatch {config.CLUSTER_SCRIPTS / '01_train_rl_agent.sh'}"
    result = subprocess.run(
        config.ssh_command(cmd),
        shell=True,
        capture_output=True,
        text=True
    )
    
    if result.returncode == 0:
        job_id = result.stdout.strip().split()[-1]
        print(f"   ✓ Job submitted: {job_id}")
        return job_id
    else:
        print(f"   ✗ Submission failed: {result.stderr}")
        return None

# ============================================================================
# MAIN
# ============================================================================

if __name__ == "__main__":
    print("=" * 70)
    print("Deploy: Train RL Agent on Cluster")
    print("=" * 70)
    
    # Compile check
    if not compile_check():
        sys.exit(1)
    
    # Deploy
    try:
        deploy_to_cluster()
        job_id = submit_job()
        
        if job_id:
            print("\n" + "=" * 70)
            print("Deployment successful!")
            print("=" * 70)
            print(f"\nJob ID: {job_id}")
            print("\nMonitor job:")
            print(f"  ssh {config.CLUSTER_USER}@{config.CLUSTER_HOST} 'squeue -j {job_id}'")
            print("\nCheck log:")
            print(f"  ssh {config.CLUSTER_USER}@{config.CLUSTER_HOST} 'tail -f {config.CLUSTER_LOGS}/rl_train_{job_id}.out'")
    
    except Exception as e:
        print(f"\n✗ Deployment failed: {e}")
        sys.exit(1)
