#!/usr/bin/env python
"""
Train RL agent on cluster - shortrest condition
Generated by 01_train_rl_agent.py
"""

import sys
from pathlib import Path
import numpy as np
import pickle

# Add src to path
SCRIPT_DIR = Path(__file__).parent
SRC_DIR = SCRIPT_DIR.parent / "src"
sys.path.insert(0, str(SRC_DIR))

from models.kuramoto import KuramotoModel, KuramotoParams
from models.energy import EnergyFunction, EnergyParams
from models.agents import QLearningAgent, AgentParams

CONDITION = "shortrest"

# ============================================================================
# ENVIRONMENT CLASS
# ============================================================================

class SynchronizationEnvironment:
    def __init__(self, kuramoto_params, energy_params, episode_duration, target_sync, input_type, input_mag):
        self.kuramoto = KuramotoModel(kuramoto_params)
        self.energy_fn = EnergyFunction(energy_params)
        self.episode_duration = episode_duration
        self.target_sync = target_sync
        self.input_type = input_type
        self.input_mag = input_mag
        self.dt = kuramoto_params.dt
        self.n_steps = int(episode_duration / self.dt)
        self.current_step = 0
        self.sync_history = []
        self.energy_history = []
    
    def reset(self):
        self.kuramoto.reset(random_phases=True)
        self.current_step = 0
        R = self.kuramoto.step()
        self.sync_history = [R]
        E = self.energy_fn.compute_energy(np.array([R]), dt=self.dt)[0]
        self.energy_history = [E]
        return R, E
    
    def step(self, action):
        # Apply action based on input type
        if self.input_type == "uniform":
            external_input = np.ones(self.kuramoto.params.n_oscillators) * action
        elif self.input_type == "split":
            external_input = np.zeros(self.kuramoto.params.n_oscillators)
            external_input[:15] = action
            external_input[15:] = -action
        else:  # none
            external_input = np.zeros(self.kuramoto.params.n_oscillators)
        
        R_next = self.kuramoto.step(external_input)
        self.sync_history.append(R_next)
        sync_array = np.array(self.sync_history)
        E_array = self.energy_fn.compute_energy(sync_array, dt=self.dt)
        E_next = E_array[-1]
        self.energy_history.append(E_next)
        reward = -abs(self.target_sync - R_next) * 100.0 - E_next
        self.current_step += 1
        done = self.current_step >= self.n_steps
        return R_next, E_next, reward, done

# ============================================================================
# TRAINING
# ============================================================================

def train_agent(agent, env, n_episodes):
    episode_rewards = []
    episode_sync_means = []
    episode_energy_means = []
    
    for episode in range(n_episodes):
        R, E = env.reset()
        episode_reward = 0.0
        
        while True:
            action_idx, action_value = agent.select_action(R, E)
            R_next, E_next, reward, done = env.step(action_value)
            agent.update(R, E, action_idx, R_next, E_next, reward)
            episode_reward += reward
            R, E = R_next, E_next
            if done:
                break
        
        agent.decay_epsilon()
        episode_rewards.append(episode_reward)
        episode_sync_means.append(np.mean(env.sync_history))
        episode_energy_means.append(np.mean(env.energy_history))
        
        if (episode + 1) % 10 == 0:
            print("Episode " + str(episode+1) + ": " +
                  "Reward=" + str(round(episode_reward, 2)) + ", " +
                  "R=" + str(round(episode_sync_means[-1], 3)) + ", " +
                  "E=" + str(round(episode_energy_means[-1], 2)))
    
    return {
        "episode_rewards": episode_rewards,
        "episode_sync_means": episode_sync_means,
        "episode_energy_means": episode_energy_means,
        "epsilon_history": agent.epsilon_history
    }

# ============================================================================
# MAIN
# ============================================================================

if __name__ == "__main__":
    print("=" * 70)
    print("Training RL Agent: " + CONDITION)
    print("=" * 70)
    
    # Initialize from config
    kuramoto_params = KuramotoParams(
        n_oscillators=31,
        coupling_strength=5.0,
        freq_mean=10.0,
        freq_std=2.0,
        dt=0.01
    )
    
    energy_params = EnergyParams(
        alpha=10.01,
        beta=5.0,
        gamma=3.0,
        delta=2.0
    )
    
    agent_params = AgentParams(
        learning_rate=0.1,
        discount_factor=0.95,
        epsilon=0.3,
        epsilon_decay=0.995,
        r_target=0.5
    )
    
    # Create environment
    env = SynchronizationEnvironment(
        kuramoto_params,
        energy_params,
        episode_duration=10.0,
        target_sync=0.5,
        input_type="split",
        input_mag=5.0
    )
    
    agent = QLearningAgent(agent_params)
    
    # Train
    print("Training...")
    results = train_agent(agent, env, n_episodes=100)
    
    # Save
    output_dir = Path("/projects/swglab/data/DMNELF/analysis/MNE/jupyter/adaptive_sync_dmnelf/models")
    output_dir.mkdir(exist_ok=True, parents=True)
    
    agent_path = output_dir / ("qlearning_" + CONDITION + ".pkl")
    agent.save(str(agent_path))
    print("Saved agent: " + str(agent_path))
    
    results_path = output_dir / ("results_" + CONDITION + ".pkl")
    with open(results_path, "wb") as f:
        pickle.dump(results, f)
    print("Saved results: " + str(results_path))
    
    print("\nFinal: Reward=" + str(round(results["episode_rewards"][-1], 2)) +
          " R=" + str(round(results["episode_sync_means"][-1], 3)) +
          " E=" + str(round(results["episode_energy_means"][-1], 2)))